# Generated by Django 3.2.7 on 2021-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
